// Mocks generated by Mockito 5.4.6 from annotations
// in planning_poker/test/presentation/views/partials/players_panel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:planning_poker/core/result/result.dart' as _i6;
import 'package:planning_poker/domain/entities/session.dart' as _i4;
import 'package:planning_poker/domain/usecases/leave_session_usecase.dart'
    as _i10;
import 'package:planning_poker/domain/usecases/play_card_usecase.dart' as _i5;
import 'package:planning_poker/domain/usecases/reset_round_usecase.dart' as _i9;
import 'package:planning_poker/domain/usecases/reveal_cards_usecase.dart'
    as _i8;
import 'package:planning_poker/domain/usecases/watch_session_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WatchSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchSessionUseCase extends _i1.Mock
    implements _i2.WatchSessionUseCase {
  MockWatchSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Session?> execute(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sessionId]),
            returnValue: _i3.Stream<_i4.Session?>.empty(),
          )
          as _i3.Stream<_i4.Session?>);
}

/// A class which mocks [PlayCardUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayCardUseCase extends _i1.Mock implements _i5.PlayCardUseCase {
  MockPlayCardUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Result<void>> execute({
    required String? sessionId,
    required String? playerId,
    required String? playerName,
    required String? cardValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #sessionId: sessionId,
              #playerId: playerId,
              #playerName: playerName,
              #cardValue: cardValue,
            }),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#execute, [], {
                  #sessionId: sessionId,
                  #playerId: playerId,
                  #playerName: playerName,
                  #cardValue: cardValue,
                }),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);
}

/// A class which mocks [RevealCardsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRevealCardsUseCase extends _i1.Mock
    implements _i8.RevealCardsUseCase {
  MockRevealCardsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Result<void>> execute(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sessionId]),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#execute, [sessionId]),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);
}

/// A class which mocks [ResetRoundUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetRoundUseCase extends _i1.Mock implements _i9.ResetRoundUseCase {
  MockResetRoundUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Result<void>> execute(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sessionId]),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#execute, [sessionId]),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);
}

/// A class which mocks [LeaveSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaveSessionUseCase extends _i1.Mock
    implements _i10.LeaveSessionUseCase {
  MockLeaveSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Result<void>> execute({
    required String? sessionId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #sessionId: sessionId,
              #playerId: playerId,
            }),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i7.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#execute, [], {
                  #sessionId: sessionId,
                  #playerId: playerId,
                }),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);
}
