// Mocks generated by Mockito 5.4.6 from annotations
// in planning_poker/test/domain/usecases/create_session_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:planning_poker/domain/entities/player.dart' as _i5;
import 'package:planning_poker/domain/entities/session.dart' as _i2;
import 'package:planning_poker/domain/repositories/session_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSession_0 extends _i1.SmartFake implements _i2.Session {
  _FakeSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i3.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Session> createSession({
    required String? name,
    required _i5.Player? host,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [], {#name: name, #host: host}),
            returnValue: _i4.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#createSession, [], {
                  #name: name,
                  #host: host,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Session>);

  @override
  _i4.Future<_i2.Session?> joinSession({
    required String? sessionKey,
    required _i5.Player? player,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinSession, [], {
              #sessionKey: sessionKey,
              #player: player,
            }),
            returnValue: _i4.Future<_i2.Session?>.value(),
          )
          as _i4.Future<_i2.Session?>);

  @override
  _i4.Future<void> leaveSession({
    required String? sessionId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveSession, [], {
              #sessionId: sessionId,
              #playerId: playerId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.Session?> watchSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSession, [sessionId]),
            returnValue: _i4.Stream<_i2.Session?>.empty(),
          )
          as _i4.Stream<_i2.Session?>);

  @override
  _i4.Future<_i2.Session?> getSessionByKey(String? sessionKey) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionByKey, [sessionKey]),
            returnValue: _i4.Future<_i2.Session?>.value(),
          )
          as _i4.Future<_i2.Session?>);

  @override
  _i4.Future<void> playCard({
    required String? sessionId,
    required String? playerId,
    required String? playerName,
    required String? cardValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#playCard, [], {
              #sessionId: sessionId,
              #playerId: playerId,
              #playerName: playerName,
              #cardValue: cardValue,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> revealCards(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#revealCards, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetRound(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#resetRound, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
